# Changes here will be overwritten by Copier
_commit: 459145c
_src_path: gh:ttoino/templates
description: Cloudflare Worker MCP server for Material Design 3 docs
name: material-mcp
project_type: worker
tests: false

